# Site Configuration
theme: jekyll-theme-dark # Change the theme to a dark theme
title: McInotti's Awesome Portfolio
description: Exploring the World of Technology
url: https://mcinotti.github.io
baseurl: ""

# Add Dark Theme Configuration
dark_theme: true

# GitHub Pages Configuration
plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

# Permalink Structure
permalink: /:year/:month/:day/:title/

# Default Layout for Posts
defaults:
  -
    scope:
      path: "" # All files in the project
      type: "posts"
    values:
      layout: "post"

# Projects Configuration
projects:
  sort_by: pushed # Sort projects by "pushed" date
  limit: 9
  exclude:
    archived: false
    forks: true

# Social Media Links
#social_media:
#  twitter: mcinotti_dev
#  linkedin: your-linkedin-username
#  website: https://www.mcinotti.com

# Topics Configuration
topics:
  - name: FreeBSD
    web_url: https://github.com/topics/freebsd
    image_url: https://d15shllkswkct0.cloudfront.net/wp-content/blogs.dir/1/files/2015/01/freebsd-devil-284x300.jpg

  - name: Linux
    web_url: https://github.com/topics/linux
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/linux/linux.png

  - name: Darwin
    web_url: https://github.com/topics/darwin
    image_url: https://avatars.githubusercontent.com/u/10107359?s=200&v=4
